### ISSUE TITLE
Code filtering potential problem

### ISSUE THREAD

**Issue by dmcglinn** [TomNash/vaccine-project#9] opened 2016-04-28 13:00 UTC
I emailed this but then realized that this is better submitted as an issue. If no filters are chosen the app suggests 126 data points are available, but the cleaned data file has 1046 records which suggests data loss at an inadvertent filtering step.

**Comment by TomNash** [comment] 2016-05-01 19:42
I just pulled the repo's current version and tried removing everything, is this how yours looks? I have 0 cases.

<img width="1440" alt="screen shot 2016-05-01 at 3 41 47 pm" src="https://cloud.githubusercontent.com/assets/8193065/14943905/41087d5c-0fb3-11e6-8181-26902770615f.png">

**Comment by dmcglinn** [comment] 2016-05-01 20:53
yea that's what I'm seeing at
http://uniola.biology.cofc.edu:3232/CFR-outbreaks/

On Sun, May 1, 2016 at 2:42 PM, Tom Nash notifications@github.com wrote:

> I just pulled the repo's current version and tried removing everything, is
> this how yours looks? I have 0 cases.
> 
> [image: screen shot 2016-05-01 at 3 41 47 pm]
> https://cloud.githubusercontent.com/assets/8193065/14943905/41087d5c-0fb3-11e6-8181-26902770615f.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/TomNash/CFR-outbreaks/issues/9#issuecomment-216067288

## 

Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by TomNash** [comment] 2016-05-01 23:47
Ah I see, when it loads it without any changes it shows 126. I'm getting the full 900+ when running locally. I tried running on shinyapps.io but I can't even get it to load. Will try running on a local Ubuntu server. The [log file](https://github.com/TomNash/CFR-outbreaks/files/244395/logs.txt) from shinyapps.io is of course useless

**Comment by dmcglinn** [comment] 2016-05-02 00:17
I didn't change your code at all so this is pretty strange

**Comment by dmcglinn** [comment] 2016-05-02 00:21
I just ran your code locally rather than via the shiny server and it produces the same 126 with no filters set.

**Comment by TomNash** [comment] 2016-05-02 01:26
It's really strange, I'm doing some debugging now. I've added comments to logs about what I've found. I'll push a change which narrows the data file down to just the 5 diseases we're looking at. What is happening is the series of checks for fatalities is evaluating all wrong.

```
2016-05-02T01:19:00.983314+00:00 shinyapps[99362]: [1] 995   6 # this is right, now just 5 diseases
2016-05-02T01:19:00.984219+00:00 shinyapps[99362]: [1] 995 # filter on type, time, outbreak: should be all 995
2016-05-02T01:19:00.984576+00:00 shinyapps[99362]: [1] "-1" # where problem occurs
2016-05-02T01:19:00.984910+00:00 shinyapps[99362]: [1] TRUE # "-1" > 0 is evaluating to TRUE
2016-05-02T01:19:00.985067+00:00 shinyapps[99362]: [1] "case1" # case where fatal instances
2016-05-02T01:19:00.985112+00:00 shinyapps[99362]: [1] 126 # narrowing down to fatal outbreaks
```

The problem is coming on the check for fatal, non-fatal, or don't care.

**Comment by TomNash** [comment] 2016-05-02 01:53
Think I fixed it. It was getting the fatality selection as a character and always evaluating to positive, making it select only outbreaks with fatalities. Should be resolved with latest push.

**Comment by dmcglinn** [comment] 2016-05-02 02:20
looks good to me the updated version is on the server. When you have time and energy you should add some text to the app describing what it's all about with a link to your webpage.

**Closed as completed** 2016-05-02 15:07 UTC
